version: "3.8"
services:
    web:
        image: iskrenm/appbg-web
        deploy:
            replicas: 5
        ports:
            - "8080:80"
        volumes:
            - ./web:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        networks:
            - app-network
    php-fpm:
        image: iskrenm/appbg-phpfpm
        deploy:
            replicas: 5 
        volumes:
            - ./web:/var/www/html
        ports:
            - "9000"
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: iskrenm/appbg-db
        ports:
            - "3306"
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
