version: "3.8"
services:
    web:
        build:
           context: .
           dockerfile: Dockerfile.web
        ports:
            - "8080:80"
        volumes:
            - ./web:/var/www/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php-fpm
        networks:
            - app-network
    php-fpm:
        build:
            context: .
            dockerfile: Dockerfile.phpfpm
        volumes:
            - ./web:/var/www/html
        ports:
            - "9000"
        networks:
            - app-network
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        ports:
            - "3306"
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
